name: assisdent-github-actions
run-name: CI/CD pipeline for Assisdent Web Client development
on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test